name: OpenAI PR Description Generator

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions: write-all

jobs:
  description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Ant0wan/openai-pr@0.0.18
        with:
          api-key: ${{ secrets.OPENAI_API_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

